version: '3.7'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=dcaf
      - POSTGRES_PASSWORD=dcaf
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/psql_data:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
volumes:
  psql_data:
    driver: local