// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use super::schema::*;
use diesel::*;

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(version))]
pub struct SchemaMigration {
    pub version: i64,
    pub dirty: bool,
}
