version: '3'

services:
    postgres:
        image: postgres:14.6-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=drip
            - POSTGRES_PASSWORD=drip
            - POSTGRES_DB=drip
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -d drip -U drip']
            interval: 5s
            timeout: 5s
            retries: 3

networks:
    default:
        name: local
