postgres:
  database: "micro"
  host: "localhost"
  port: 5432
  user: "docker"
  password: "docker"
  sslmode: false

redis:
  host: "localhost"
  port: 6379
  password: "docker"

rabbitmq:
  host: "localhost"
  port: 6379
  user: "docker"
  password: "docker"

