postgres:
  database: "micro"
  host: "localhost"
  port: 5432
  user: "docker"
  password: "docker"
  sslmode: "disable"

redis:
    host: 'localhost'
    port: 6379
    password: 'docker'

rabbitmq:
  host: "localhost"
  port: 5672
  user: "docker"
  password: "docker"
