[features]
seeds = true
skip-lint = false

[programs.localnet]
drip_v2 = "74XYB4agZ83msRxmTGvNDc8D2z8T55mfGfz3FAneNSKk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./local.json"

[scripts]
test = "yarn test"
testd = "TEST_MODE=debug anchor test"
