[features]
seeds = true
skip-lint = false

[programs.localnet]
drip_v2 = "74XYB4agZ83msRxmTGvNDc8D2z8T55mfGfz3FAneNSKk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 --parallel tests/**/*.ts"
