openapi: 3.0.0
info:
  title: Drip Backend
  description: |
    Drip backend service.
    All API's have a IP rate limit of 10 requests per second.
  contact:
    email: mocha@dcaf.so
    name: Mocha
  version: 1.0.0

paths:
  /:
    get:
      summary: Health Check
      description: Ping api.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/pingResponse"

components:
  schemas:
    pingResponse:
      required:
        - message
      properties:
        message:
          type: string
