anchor_version = "0.28.0"
solana_version = "1.16.10"

[features]
seeds = true
skip-lint = false

[programs.localnet]
drip_v2 = "74XYB4agZ83msRxmTGvNDc8D2z8T55mfGfz3FAneNSKk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./local.json"

[scripts]
test = "node scripts/test.js"

[test]
startup_wait = 10000
