version: '3'

services:
  postgres:
    image: postgres:14.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=micro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d micro -U docker"]
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass docker
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: docker
      RABBITMQ_DEFAULT_PASS: docker
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  default:
    name: local
