// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use super::schema::*;
use diesel::*;

use chrono::NaiveDateTime;
#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(public_key))]
pub struct AccountQueueItem {
    pub public_key: String,
    pub priority: i32,
    pub attempts: i32,
    pub max_attempts: i32,
    pub time: NaiveDateTime,
    pub retry_time: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(version))]
pub struct SchemaMigration {
    pub version: i64,
    pub dirty: bool,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(tx_signature))]
pub struct TxQueueItem {
    pub tx_signature: String,
    pub priority: i32,
    pub attempts: i32,
    pub max_attempts: i32,
    pub time: NaiveDateTime,
    pub retry_time: Option<NaiveDateTime>,
}
